---
- name: Install Apache
  hosts: test_ssh  # hosts in the inventory file
  remote_user: root  # name of the user to ssh into remote

  # internal vars
  vars:
    var_group:
      var_a: value-a
      var_b: value-b
  # External vars file
  vars_files:
    - vars/secrets.yaml

  # Handers can be run after a task is executed by notifying
  handlers:
    - name: restart apache
      service:
        name: apache2
        state: restarted
        enabled: true  # enable after restart
  # initiate the tasks of roles
  roles:
    # directory name under roles directory
    - curl
    # install galaxy package via ansible-galaxy
    # - geerlingguy.java 
  tasks: 
    # Task Management
    # Create a file for tasks and import it
    # if import_tasks doesnt' work try include_tasks
    - import_tasks: tasks/apache.yaml
    # install curl using role but amang tasks
    - include_role: 
        name: curl
    - name: display environment 
      shell: "echo $ENV_VAR_A $ENV_VAR_B secret password is $PASSWORD "
      # if there are no changes made, tell ansible by passing changed_when
      changed_when : false
      # set environment variables in shell
      environment : 
        - ENV_VAR_A: "{{ var_group['var_a'] }}"
        - ENV_VAR_B: "{{ var_group['var_b'] }}"
        - PASSWORD : "{{ secret_password }}"
      # export the output of the execution
      register: env_out
    # To view the output of a command in ansible
    - debug:
        msg: "{{ env_out.stdout }}"
        