---
- name : Install Apache
  hosts : test_ssh
  remote_user : root

  tasks : 
  - name : Installing apache2
    apt:
      name : apache2
      state : present

  - name : ensure apache2 start
    service:
      name : apache2
      state: started
      enabled : true